"""``docs/API_CONTRACT.md`` is checked against the application, not trusted.

The document is the only thing a separate frontend build has. Nobody who reads
it can ask a follow-up question, so every drift between it and the code becomes
a frontend bug that surfaces at integration time. These tests are what stop that:
the endpoint set, the error-code set and the enum members are all compared
against the running application rather than against anybody's memory.

**The route inventory comes from ``application.openapi()``, deliberately.**
Phase 12 found that a naive walk over ``app.routes`` returns *nothing* under
FastAPI 0.141 — each ``include_router`` call is wrapped in an ``_IncludedRouter``
that keeps the original router and exposes no ``routes`` attribute of its own --
and a route audit built on it passed by finding no routes at all. The OpenAPI
document is generated by FastAPI from the same routers and cannot be empty
without the application being empty, so it is the authority here.
``tests/integration/test_security_sweep.py`` keeps a hand-written walk and
asserts it agrees with this same document, which is where that bug would surface
again.
"""

from __future__ import annotations

import ast
import collections
import re
from pathlib import Path

import pytest

from app.attestation.trust import TrustLevel
from app.config import get_settings
from app.core.errors import ErrorCode
from app.db.models import enums
from app.media.mirror import Tier
from app.verification.anomaly import SignalCode
from app.verification.claiming import ClaimStatus
from app.verification.schemas import VerificationResult
from app.verification.service import _IDENTIFYING_KEY_PARTS

pytestmark = pytest.mark.contract

CONTRACT = Path(__file__).resolve().parents[2] / "docs" / "API_CONTRACT.md"

# Endpoints are declared as level-four headings holding a method and a path in
# backticks, e.g. "#### `POST {API_PREFIX}/items`".
_HEADING = re.compile(r"^#### `([A-Z]+) (\S+)`\s*$", re.M)

# Words that mean the document was left unfinished, plus one that names a thing
# this project does not have. Case-insensitive.
_FORBIDDEN = ("tbd", "todo", "probably", "should be", "github")


def contract_text() -> str:
    return CONTRACT.read_text(encoding="utf-8")


def documented_operations() -> set[str]:
    """``{"get /api/v1/items", ...}`` — the document's endpoint set, resolved.

    ``{API_PREFIX}`` in the document is substituted with the configured prefix so
    the comparison is against real paths rather than against a placeholder.
    """
    prefix = get_settings().api_prefix
    return {
        f"{method.lower()} {path.replace('{API_PREFIX}', prefix)}"
        for method, path in _HEADING.findall(contract_text())
    }


def _section(heading: str, until: str) -> str:
    """The document text between two headings. Both must be present."""
    text = contract_text()
    assert heading in text, f"{heading} is missing from docs/API_CONTRACT.md"
    body = text.split(heading, 1)[1]
    return body.split(until, 1)[0] if until in body else body


def _codes_in_error_tables() -> set[str]:
    """Codes tabulated in section 4 and section 4.1, from the leading cell.

    A row there begins ``| `CODE` |``. Nothing else in the document has that
    shape, so this cannot pick up prose.
    """
    return set(
        re.findall(r"^\| `([A-Z][A-Z0-9_]+)`", _section("## 4. Error codes", "## 5."), re.M)
    )


# The status each exception class answers with when the raise site does not say.
_DEFAULT_STATUS = {
    "AppError": 500,
    "AuthError": 401,
    "ChainUnavailable": 503,
    "ConflictError": 409,
    "ForbiddenError": 403,
    "InsufficientStorageError": 507,
    "NotFoundError": 404,
    "RateLimitError": 429,
    "UnavailableError": 503,
    "ValidationError": 422,
}

APP_DIR = Path(__file__).resolve().parents[2] / "app"


def statuses_raised_in_source() -> dict[str, set[int]]:
    """``{"MEDIA_TOO_LARGE": {413}, ...}`` read out of ``app/``.

    A static read, and deliberately a partial one: a code raised through a
    helper that takes the code as an argument -- ``app.catalog.validator._reject``
    is the one that does -- is invisible here. So this is only ever used to
    contradict the document, never to demand that a code appear. A code this
    cannot resolve is simply not checked.
    """
    found: dict[str, set[int]] = collections.defaultdict(set)
    for path in APP_DIR.rglob("*.py"):
        if path.as_posix().endswith("core/errors.py"):
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not isinstance(node, ast.Call):
                continue
            function = node.func
            name = (
                function.id
                if isinstance(function, ast.Name)
                else getattr(function, "attr", None)
            )
            if name not in _DEFAULT_STATUS:
                continue
            code = status = None
            for keyword in node.keywords:
                if keyword.arg == "code" and isinstance(keyword.value, ast.Attribute):
                    code = keyword.value.attr
                if keyword.arg == "status" and isinstance(keyword.value, ast.Constant):
                    status = keyword.value.value
            if code is not None:
                found[code].add(status or _DEFAULT_STATUS[name])
    return dict(found)


def documented_statuses() -> dict[str, set[int]]:
    """Every ``| `CODE` | <status> |`` row in the document, by code."""
    rows = re.findall(
        r"^\| `([A-Z][A-Z0-9_]+)` \| (\d{3})",
        contract_text(),
        re.M,
    )
    found: dict[str, set[int]] = collections.defaultdict(set)
    for code, status in rows:
        found[code].add(int(status))
    return dict(found)


def served_operations() -> set[str]:
    from app.main import create_app

    schema = create_app().openapi()
    return {
        f"{method.lower()} {path}"
        for path, operations in schema["paths"].items()
        for method in operations
    }


class TestTheDocumentExists:
    def test_the_contract_is_present(self) -> None:
        assert CONTRACT.is_file(), f"{CONTRACT} does not exist"

    def test_the_heading_pattern_actually_matches_something(self) -> None:
        """Guards against the whole suite passing on a regex that matches nothing.

        Every assertion below compares two sets. A parser that silently returns
        an empty set would make the set-difference checks trivially pass in one
        direction and blame the application in the other, which is exactly the
        failure mode the route-inventory bug had in Phase 12.
        """
        assert len(documented_operations()) >= 40


class TestEndpointSets:
    def test_the_document_and_the_application_serve_the_same_endpoints(self) -> None:
        documented = documented_operations()
        served = served_operations()

        undocumented = sorted(served - documented)
        phantom = sorted(documented - served)

        assert not undocumented, (
            "these endpoints are served by the application and are absent from "
            f"docs/API_CONTRACT.md: {undocumented}. A frontend reading the "
            "contract would never know they exist."
        )
        assert not phantom, (
            "these endpoints are documented in docs/API_CONTRACT.md and are not "
            f"served by the application: {phantom}. A frontend would call them "
            "and get a 404."
        )

    def test_the_operation_count_in_the_prose_is_right(self) -> None:
        """Section 3 opens by naming a number. Numbers in prose go stale."""
        stated = re.search(r"^(\d+) operations\.", contract_text(), re.M)
        assert stated is not None, "section 3 no longer states an operation count"
        assert int(stated.group(1)) == len(served_operations())

    def test_no_endpoint_is_documented_twice(self) -> None:
        headings = _HEADING.findall(contract_text())
        seen: set[tuple[str, str]] = set()
        duplicates = sorted(
            f"{method} {path}"
            for method, path in headings
            if (method, path) in seen or seen.add((method, path))  # type: ignore[func-returns-value]
        )
        assert not duplicates, f"documented more than once: {duplicates}"


class TestErrorCodes:
    def test_every_code_named_in_the_document_exists_in_the_enum(self) -> None:
        """A documented code the application cannot emit is a dead branch.

        Read from the leading cell of a section-4 table row rather than from
        every backticked capital in the file. Prose in this document legitimately
        names environment variables, a sample tag code, and the six codes that
        were deleted in this phase; a heuristic loose enough to catch a wrong
        error code is loose enough to catch all of those, and a check that fires
        on prose is a check somebody switches off.
        """
        known = {member.name for member in ErrorCode}
        invented = sorted(_codes_in_error_tables() - known)
        assert not invented, (
            "docs/API_CONTRACT.md tabulates these as error codes and "
            f"app/core/errors.py has no such member: {invented}"
        )

    def test_the_error_table_is_not_empty(self) -> None:
        """The check above compares two sets; one of them must be real."""
        assert len(_codes_in_error_tables()) >= 40

    def test_no_documented_status_contradicts_the_raise_site(self) -> None:
        """Catches the class of error a reader cannot catch by reading.

        A wrong status in a frozen contract is a frontend that branches on the
        wrong number, and nothing about the document itself looks wrong. Two of
        these were found by hand while writing it -- ``MEDIA_TOO_LARGE`` is 413
        and ``CATEGORY_RETIRED`` is 422, and both had been written down from the
        shape of the error rather than from the raise site.
        """
        in_source = statuses_raised_in_source()
        wrong: list[str] = []
        for code, documented in sorted(documented_statuses().items()):
            actual = in_source.get(code)
            if actual is None:
                continue
            unexplained = documented - actual
            if unexplained:
                wrong.append(
                    f"{code}: documented as {sorted(unexplained)}, "
                    f"raised in app/ as {sorted(actual)}"
                )
        assert not wrong, (
            "docs/API_CONTRACT.md disagrees with the raise sites:\n" + "\n".join(wrong)
        )

    def test_the_status_scan_resolves_most_codes(self) -> None:
        """The check above is only meaningful while the scan sees real codes."""
        assert len(statuses_raised_in_source()) >= 40

    def test_every_code_in_the_enum_appears_in_the_document(self) -> None:
        text = contract_text()
        missing = sorted(
            member.name for member in ErrorCode if f"`{member.name}`" not in text
        )
        assert not missing, (
            "these error codes exist in app/core/errors.py and are absent from "
            f"docs/API_CONTRACT.md: {missing}. Either document them, or delete "
            "them if nothing raises them."
        )

    def test_every_code_appears_in_the_reachability_table(self) -> None:
        """Section 4.1 maps each code to a test that triggers it.

        A code documented with no reachable trigger is either dead or untested,
        and the table is where that gets decided rather than forgotten.
        """
        text = contract_text()
        table = text.split("### 4.1 Reachability", 1)
        assert len(table) == 2, "section 4.1 is missing from docs/API_CONTRACT.md"

        reachability = table[1]
        missing = sorted(
            member.name for member in ErrorCode if f"`{member.name}`" not in reachability
        )
        assert not missing, (
            "these error codes are documented but do not appear in the "
            f"reachability table in section 4.1: {missing}"
        )


# Enums whose members reach a client as JSON values. Every member of each must be
# named in the document, because a frontend switching on one needs the whole set.
_WIRE_ENUMS: dict[str, type] = {
    "UserRole": enums.UserRole,
    "UserStatus": enums.UserStatus,
    "ItemStatus": enums.ItemStatus,
    "DisputeStatus": enums.DisputeStatus,
    "ItemEventType": enums.ItemEventType,
    "MediaKind": enums.MediaKind,
    "PinStatus": enums.PinStatus,
    "SuspicionLevel": enums.SuspicionLevel,
    "OutboxJobType": enums.OutboxJobType,
    "OutboxStatus": enums.OutboxStatus,
    "TrustLevel": TrustLevel,
    "VerificationResult": VerificationResult,
    "ClaimStatus": ClaimStatus,
    "SignalCode": SignalCode,
    "Tier": Tier,
}

# Enums that never appear as a JSON value anywhere in this API, with the reason.
# Listed rather than omitted so that a member added to one of them prompts a
# decision instead of quietly slipping past the check above.
_INTERNAL_ENUMS: dict[str, str] = {
    "AuthEventType": "the append-only auth audit table; no endpoint returns it",
    "DisputeSource": "internal dispute bookkeeping; no route serialises it",
    "ChainTxStatus": (
        "the transaction lifecycle. The payloads project item status instead, "
        "and CONFIRMED/FAILED collide with ItemStatus by coincidence"
    ),
    "OAuthProvider": (
        "never a JSON field value. /auth/oauth/providers returns the lowercase "
        "registry name 'google', not the enum member"
    ),
}


class TestEnums:
    def test_the_two_enum_lists_cover_every_enum_in_the_models_module(self) -> None:
        """A new enum has to be classified, not silently ignored."""
        declared = {
            name
            for name in enums.__all__
            if isinstance(getattr(enums, name, None), type)
            and hasattr(getattr(enums, name), "__members__")
        }
        classified = set(_WIRE_ENUMS) | set(_INTERNAL_ENUMS)
        unclassified = sorted(declared - classified)
        assert not unclassified, (
            f"these enums are neither listed as on-the-wire nor as internal: "
            f"{unclassified}. Decide which, and document the members if they "
            "reach a client."
        )

    @pytest.mark.parametrize("name", sorted(_WIRE_ENUMS))
    def test_every_member_of_a_wire_enum_is_documented(self, name: str) -> None:
        text = contract_text()
        missing = sorted(
            member
            for member in _WIRE_ENUMS[name].__members__
            if f"`{member}`" not in text
        )
        assert not missing, (
            f"{name} members reach a client as JSON and are absent from "
            f"docs/API_CONTRACT.md: {missing}"
        )


class TestPublicPayloadRules:
    def test_the_withheld_attribute_keys_are_listed_in_full(self) -> None:
        """The document claims a complete denylist, so it has to stay complete.

        A public page is built against this list -- it is what tells a frontend
        that a key present in the category schema may be absent from the public
        payload. A part added to `_IDENTIFYING_KEY_PARTS` and not to the document
        makes the document quietly wrong about the one thing on this surface
        that protects a person's name.
        """
        text = contract_text()
        missing = sorted(part for part in _IDENTIFYING_KEY_PARTS if f"`{part}`" not in text)
        assert not missing, (
            "app.verification.service withholds attribute keys containing these "
            f"substrings and docs/API_CONTRACT.md does not name them: {missing}"
        )


class TestProse:
    @pytest.mark.parametrize("word", _FORBIDDEN)
    def test_the_document_carries_no_placeholder_language(self, word: str) -> None:
        """Unfinished prose in a frozen contract is a frontend bug in waiting.

        `github` is in the list for a different reason: this project has one
        OAuth provider and it is Google. The word appearing here would mean the
        document had drifted into describing something that does not exist.
        """
        offenders = [
            f"line {number}: {line.strip()}"
            for number, line in enumerate(contract_text().splitlines(), start=1)
            if word in line.lower()
        ]
        assert not offenders, (
            f"docs/API_CONTRACT.md contains {word!r}:\n" + "\n".join(offenders)
        )

    def test_the_document_states_that_it_is_frozen(self) -> None:
        assert "frozen" in contract_text().lower()

    def test_the_versioning_rule_is_stated_in_the_document(self) -> None:
        text = contract_text()
        assert "## 6. Versioning" in text
        section = text.split("## 6. Versioning", 1)[1]
        assert "Additive changes do not bump the version" in section
        assert "Breaking changes require a new" in section

    def test_the_public_mount_is_documented_as_outside_the_api_prefix(self) -> None:
        """The single most expensive thing to get wrong in a frontend build.

        A client that assumes /api/v1/v/{tag_code} calls a path this service does
        not serve, and the printed QR would never have reached it anyway.
        """
        assert "NOT under `/api/v1`" in contract_text()
